services:
  app:
    image: node:24-alpine
    container_name: quizzy-node
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.docker
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/quizzy
      NODE_ENV: development
    command: >
      sh -c "npm install &&
             npx prisma generate &&
             npx prisma migrate deploy &&
             npm run dev"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: quizzy-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quizzy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /Users/arslankaleem/Workspace/Junk/linkedin-skill-assessments-quizzes

volumes:
  postgres_data:
