services:
  app:
    build: .
    container_name: quizzy-node
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /Users/arslankaleem/Workspace/Junk/linkedin-skill-assessments-quizzes:/Users/arslankaleem/Workspace/Junk/linkedin-skill-assessments-quizzes

    ports:
      - "3000:3000"

    env_file:
      - .env
      - .env.docker

    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/quizzy-v1
      SHADOW_DATABASE_URL: postgres://postgres:password@localhost:5432/shadow_db
      NODE_ENV: development

    command: npm run dev

    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: quizzy-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quizzy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /Users/arslankaleem/Workspace/Junk/linkedin-skill-assessments-quizzes

volumes:
  postgres_data:
