services:
  app:
    build: .
    container_name: quizzy-node
    # command: npm run dev
    # working_dir: /app
    # volumes:
    #   - .:/app
    #   - /app/node_modules

    ports:
      - "3000:3000"

    env_file:
      - .env.docker

    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
    #   - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    #   - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    #   - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    #   - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
    #   - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
    #   - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    #   - DEEPSEEK_API_BASE_URL=${DEEPSEEK_API_BASE_URL}
    #   - APP_URL=${APP_URL}
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
    #   - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    #   - S3_REGION=${S3_REGION}
    #   - S3_BUCKET_NAME=${S3_BUCKET_NAME}

    depends_on:
      - redis
      - postgres

    restart: unless-stopped

  # worker:
  #   build: .
  #   container_name: worker
  #   command: npx tsx worker/gen-ai-worker.ts

  #   env_file:
  #     - .env
  #     - .env.docker
  #   depends_on:
  #     - redis
  #     - postgres

  postgres:
    image: postgres:17
    container_name: quizzy-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quizzy-v1

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

  redis:
    image: redis:8.4-alpine
    container_name: quizzy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
